// Generated by dts-bundle v0.7.3-fork.1
// Dependencies for this module:
//   ../../../../../moment
//   ../../../../../@fullcalendar/core

declare module '@fullcalendar/moment' {
    import { Calendar, Duration } from '@fullcalendar/core';
    const _default: import("@fullcalendar/core").PluginDef;
    export default _default;
}

